### ISSUE TITLE
Official awesome list

### ISSUE THREAD

**Issue by Sytten** [hahwul/CaidoTweaks#1]
Hi! Thanks for starting this, I created an "official" awesome list for caido here: https://github.com/caido/awesome
Best, Emile

**Comment by hahwul** [comment]
@Sytten 
Wow, there's now an official awesome list! I'll make a PR to the official repo if I have something to add :D

**Comment by hahwul** [comment]
Hello agin @Sytten 
I've added a notice to my repository to guide you to the official repository. 
This repository has been archived and made public.

See you at the official repository! :D
